import { dayOfYear, type ISODate } from "./dates";

/** Frases originales de Data Edge Finanzas. Se elige una por día según la fecha. */
export const QUOTES: string[] = [
  "Cada peso que administras bien hoy mejora tus opciones mañana.",
  "El dinero que no tiene destino suele encontrar uno que no elegiste.",
  "Un presupuesto no te quita libertad: te dice cuánta tienes.",
  "Registrar un gasto toma segundos; entenderlo puede cambiar un año.",
  "Tu saldo de hoy es una foto. Tu flujo de caja es la película.",
  "Ahorrar no es lo que sobra: es lo primero que decides.",
  "La tranquilidad financiera se construye con decisiones pequeñas y repetidas.",
  "Lo que se mide, se puede mejorar. Lo que no, se adivina.",
  "Una deuda sin plan crece; una deuda con plan se acaba.",
  "El mejor momento para mirar tus números es antes de necesitarlos.",
  "Gastar bien también es una forma de ahorrar.",
  "Tus metas necesitan fecha, monto y un primer aporte.",
  "El fondo de emergencia es el seguro que tú mismo te pagas.",
  "No se trata de ganar más de inmediato, sino de saber a dónde va lo que ganas.",
  "Cada suscripción olvidada es un gasto que decide por ti.",
  "La claridad sobre tu dinero reduce más estrés que cualquier atajo.",
  "Un mes ordenado es el mejor punto de partida para el siguiente.",
  "Anticipar un pago es más barato que improvisarlo.",
  "Tu calendario también habla de tu dinero. Escúchalo.",
  "Decidir con datos es decidir con calma.",
  "La disciplina financiera empieza con un hábito de cinco minutos.",
  "Pagar la tarjeta completa es ganarle una tasa al banco.",
  "El interés compuesto trabaja para ti o contra ti. Tú eliges el lado.",
  "Pequeños ajustes sostenidos superan a los grandes cambios que no duran.",
  "El dinero es una herramienta; el plan es lo que la hace útil.",
  "Conocer tu punto de equilibrio personal te da poder de negociación.",
  "Antes de comprar, pregúntate cuántas horas de trabajo cuesta.",
  "Tu patrimonio crece cuando tus activos le ganan a tus pasivos.",
  "Una meta visible es una meta que avanza.",
  "La liquidez es la libertad de no tener que decir que sí a todo.",
  "Revisar tus movimientos no es desconfianza: es cuidado.",
  "Separar necesidades de deseos también es una forma de respeto por tu esfuerzo.",
  "El orden en tus cuentas se nota en la calma de tus decisiones.",
  "Los ingresos variables piden presupuestos conservadores.",
  "No compares tu dinero con el de otros; compáralo con tu plan.",
  "Una prima bien usada puede adelantar una meta varios meses.",
  "El ahorro automático es la fuerza de voluntad que no se cansa.",
  "Cada cuota que eliminas libera espacio para lo que importa.",
  "Tu futuro financiero se escribe con los gastos de esta semana.",
  "El mejor gasto es el que planeaste y disfrutaste sin culpa.",
  "Tener efectivo disponible es comprar tiempo para pensar.",
  "Conocer tus fechas de corte es tener ventaja sobre tu tarjeta.",
  "Una familia que habla de dinero decide mejor.",
  "Enseñar finanzas en casa es la herencia que más rinde.",
  "No hay inversión más rentable que salir de una deuda cara.",
  "Diversificar es no depender de una sola buena noticia.",
  "Lo que no está en el presupuesto termina en la tarjeta.",
  "Tu tasa de ahorro dice más de tu futuro que tu salario.",
  "El control no es restricción: es dirección.",
  "Planear el mes siguiente empieza por cerrar bien este.",
  "Si un gasto se repite, merece una categoría y una revisión.",
  "El dinero ordenado te deja tiempo para lo que no se compra.",
  "Cada ingreso extra tiene tres opciones: deuda, meta o disfrute. Elige a propósito.",
  "Tus números no te juzgan; te orientan.",
  "Una proyección no adivina el futuro: te prepara para él.",
  "Saber cuándo llega tu dinero es tan importante como saber cuánto llega.",
  "Ahorra para lo previsible y asegura lo imprevisible.",
  "Hoy es buen día para revisar una suscripción que ya no usas.",
  "Pagar a tiempo también construye patrimonio: el de tu reputación.",
  "El flujo de caja positivo es el oxígeno de cualquier plan.",
  "Invertir sin fondo de emergencia es construir sin cimientos.",
  "Tu mejor versión financiera empieza con honestidad sobre tus gastos.",
  "El dinero que entiendes es dinero que puedes hacer crecer.",
  "Un gasto hormiga al día es un viaje al año.",
  "Negociar tus tarifas es un aumento que te das tú mismo.",
  "Los impuestos también se planean: no dejes que te sorprendan.",
  "Un mes sin registros es un mes que no podrás explicar.",
  "La meta no es gastar menos; es gastar mejor.",
  "Cada decisión informada suma, aunque parezca pequeña.",
  "Tus finanzas personales son la empresa más importante que diriges.",
  "El patrimonio no se mide por lo que muestras, sino por lo que conservas.",
  "Proteger tus ingresos es tan importante como aumentarlos.",
  "Un plan simple que cumples vale más que uno perfecto que abandonas.",
  "Cuando sabes cuánto necesitas, sabes cuándo es suficiente.",
  "Revisa tu presupuesto como revisas el clima: antes de salir.",
  "La constancia convierte aportes pequeños en resultados grandes.",
  "Cada cuenta en orden es una preocupación menos.",
  "Antes de endeudarte, calcula la cuota y el costo total.",
  "Tu dinero debería trabajar al menos tan duro como tú.",
  "Las emergencias no avisan, pero sí se pueden anticipar.",
  "Un ingreso fijo con gastos variables pide vigilancia semanal.",
  "El mejor momento para empezar a ahorrar fue ayer; el segundo es hoy.",
  "Saber decir no a un gasto es decir sí a una meta.",
  "Tu calendario financiero es tu mapa para no tomar desvíos caros.",
  "Invertir es sembrar; ahorrar es preparar la tierra.",
  "La información confiable es la base de toda buena decisión.",
  "Reducir un gasto fijo rinde todos los meses.",
  "Una familia con metas compartidas rema en la misma dirección.",
  "Tener un plan para cada peso no es rigidez: es intención.",
  "Tus hábitos financieros de hoy son tu patrimonio de mañana.",
  "Celebra los avances: pagar una deuda también es una meta cumplida.",
  "Conocer tu costo de vida real es el primer paso hacia la independencia.",
  "El ahorro que no se toca tiene nombre y propósito.",
  "Evita que el saldo disponible se confunda con dinero libre.",
  "La prosperidad es la suma de muchas decisiones aburridas bien tomadas.",
  "Mirar hacia adelante con números reduce la incertidumbre.",
  "Cada meta alcanzada te enseña cómo lograr la siguiente.",
  "Organizar tu dinero es organizar tu tiempo.",
  "Menos sorpresas en el extracto, más tranquilidad en casa.",
  "Tu dinero. Tu familia. Tus decisiones.",
];

export function quoteForDate(iso: ISODate): string {
  const year = Number(iso.slice(0, 4));
  return QUOTES[(dayOfYear(iso) + year * 7) % QUOTES.length];
}
